/* 
CIS 353
 - Database Design Project 
Aaron Teague
Kyle Hekhuis
Mattie Phillips
Michael Strating
*/ 


DROP TABLE BREWERY CASCADE CONSTRAINTS;
DROP TABLE FOOD CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE JOB CASCADE CONSTRAINTS;
DROP TABLE DISTRIBUTOR CASCADE CONSTRAINTS;
DROP TABLE BEER CASCADE CONSTRAINTS;
DROP TABLE BATCH CASCADE CONSTRAINTS;
DROP TABLE SEASON CASCADE CONSTRAINTS;
DROP TABLE INGREDIENTS CASCADE CONSTRAINTS;
DROP TABLE CERTIFIED CASCADE CONSTRAINTS;

CREATE TABLE BREWERY(
BreweryID	INTEGER PRIMARY KEY,
Name		VARCHAR2(60) NOT NULL,
Location	VARCHAR2(180)
);


CREATE TABLE FOOD(
FoodID		INTEGER PRIMARY KEY, 
Name		VARCHAR2(30) NOT NULL, 
BreweryID	INTEGER NOT NULL,
CONSTRAINT Food_BreweryExistConst FOREIGN KEY (BreweryID) REFERENCES BREWERY(BreweryID)
	ON DELETE CASCADE
	DEFERRABLE INITIALLY DEFERRED
);


CREATE TABLE EMPLOYEE(
EmpID		INTEGER PRIMARY KEY, 
Name		VARCHAR2(30) NOT NULL, 
Salary		INTEGER NOT NULL, 
Address		VARCHAR2(180), 
PhoneNumber	INTEGER, 
BreweryID	INTEGER NOT NULL, 
MangerID	INTEGER,
CONSTRAINT Employee_BreweryExistConst FOREIGN KEY (BreweryID) REFERENCES BREWERY(BreweryID)
	ON DELETE CASCADE
	DEFERRABLE INITIALLY DEFERRED,
CONSTRAINT ManagerIsEmpConst FOREIGN KEY (MangerID) REFERENCES EMPLOYEE(EmpID)
	DEFERRABLE INITIALLY DEFERRED
);


CREATE TABLE JOB(
JobID		INTEGER PRIMARY KEY,
Title		VARCHAR2(20)
);


CREATE TABLE DISTRIBUTOR(
DistID		INTEGER PRIMARY KEY,
Name		VARCHAR2(20),
Location	VARCHAR2(20),
ContractStart	DATE,
BreweryID	INTEGER,
CONSTRAINT  Distributor_BreweryExistConst FOREIGN KEY(BreweryID) REFERENCES BREWERY(BreweryID)
	ON DELETE CASCADE
	DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE SEASON(
SeasonID		CHAR(5) PRIMARY KEY,
StartDate		DATE,
EndDate			DATE,
CONSTRAINT ValidSeason CHECK(SeasonID IN('Su','Sp','F','W','FW','WS','SpSu','SuF','All','FWSp','SuFW','WSpSu','SpSuF') ) );

CREATE TABLE BEER(
BeerID		INTEGER PRIMARY KEY,
Name		VARCHAR(300),
SeasonID	CHAR(5),
Type		VARCHAR(20),
Abv			DECIMAL,
BreweryID	INTEGER,
CONSTRAINT Beer_SeasonConst FOREIGN KEY(SeasonID) REFERENCES SEASON(SeasonID)
	ON DELETE CASCADE
	DEFERRABLE INITIALLY DEFERRED,
CONSTRAINT Beer_BreweryExistConst FOREIGN KEY(BreweryID) REFERENCES BREWERY(BreweryID),
CONSTRAINT AbvConst CHECK (Abv < 9.51),
CONSTRAINT LightTypeConst CHECK (NOT (Type = 'light' AND (Abv > 2.29 OR Abv < 4.50))),
CONSTRAINT RegTypeConst CHECK (NOT (Type = 'regular' AND (Abv < 9.51))),
CONSTRAINT NonalcTypeConst CHECK (NOT (Type = 'non-alcoholic' AND (Abv >= 0.1 OR Abv > 0.74))),
CONSTRAINT TypeConst CHECK (Type IN ('light', 'regular', 'non-alcoholic'))
);


CREATE TABLE BATCH(
BeerID		INTEGER,
EmpID		INTEGER,
BatchDate	DATE,
PH			INTEGER,
Color		CHAR(10),
PRIMARY KEY (BeerID, EmpID, BatchDate),
CONSTRAINT Batch_BeerConst FOREIGN KEY(BeerID) REFERENCES BEER(BeerID)
	ON DELETE CASCADE
	DEFERRABLE INITIALLY DEFERRED,
CONSTRAINT Batch_EmployeeConst FOREIGN KEY(EmpID) REFERENCES EMPLOYEE(EmpID)
	ON DELETE CASCADE
	DEFERRABLE INITIALLY DEFERRED
--CONSTRAINT Batch_CertifiedConst CHECK(EmpId IN (SELECT C.EmpId FROM CERTIFIED C where C.JobId = 3))
--Not sure about the syntax here, the first EmpId may need to be changed to be VALUE and be declared underneath where EmpId is declared
);
    

CREATE TABLE INGREDIENTS(
BeerID		INTEGER,
Ingredient	CHAR(30),
PRIMARY KEY (BeerID, Ingredient)    
);


CREATE TABLE CERTIFIED(
EmpID		INTEGER,
JobID		INTEGER,
PRIMARY KEY(EmpID, JobID)
);
